### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by salamtura** [orlyapps/nova-workflow#1]
Hello,

It seems the link to the documentation is not working. It's a brilliant package and I would like to use it for my project. Kindly help!

**Comment by scramatte** [comment]
Where is the doc?

**Comment by cadicservices** [comment]
Thanks for the documentation. I'm really looking forward to testing this package.

**Comment by arnoteruel** [comment]
Thanks for the documentation. I'm really looking forward to testing this package.

**Comment by orlyapps** [comment]
well my plan is do document this package more with the release of nova 4.0

**Comment by orlyapps** [comment]
See Progress here: https://github.com/orlyapps/nova-workflow/pull/3
